<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Visio</title>

    <link rel="stylesheet" href="<?= phpb_asset('pagebuilder/bootstrap-v4.3.1.min.css') ?>">
    <link rel="stylesheet" href="<?= phpb_asset('pagebuilder/bootstrap-select-v1.13.12.min.css') ?>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css">

    <link href="<?= phpb_asset('websitemanager/app.css') ?>" rel="stylesheet">
</head>
<body class="bg-light">

<div class="container">
    <div id="welcome-page">

        <h1 class="text-center">Welcome to Visio</h1>

        <div class="text-center intro-links">
            <a href="<?= phpb_url('website_manager') ?>">Get started</a>
            <a href="https://github.com/nomadicjosh/visio"><i class="fab fa-github"></i> Visit GitHub</a>
        </div>

    </div>
</div>

<script src="<?= phpb_asset('pagebuilder/jquery-3.4.1.min.js') ?>"></script>
<script src="<?= phpb_asset('pagebuilder/popper-v1.12.9.min.js') ?>"></script>
<script src="<?= phpb_asset('pagebuilder/bootstrap-v4.3.1.min.js') ?>"></script>
<script src="<?= phpb_asset('pagebuilder/bootstrap-select-v1.13.12.min.js') ?>"></script>
<script src="<?= phpb_asset('websitemanager/app.js') ?>"></script>
</body>
</html>
