<?php

use function Codefy\Framework\Helpers\config;
use function Codefy\Framework\Helpers\gate;
use function Codefy\Framework\Helpers\trans;
?>

<?php if(false === gate('admin:dashboard')): ?>
    <nav id="nav-menu" class="hidden md:flex space-x-4">
        <a href="/<?=config(key: 'auth.login_route');?>/">
        <button
                class="inline-flex items-center py-2 px-6 bg-gradient-to-r from-indigo-700 to-pink-600 hover:bg-opacity-95 text-white rounded-md"
        >
            <?=trans('Login');?>
        </button>
        </a>
    </nav>

<?php else: ?>
    <nav id="nav-menu" class="hidden md:flex space-x-4">
        <div x-cloak x-data="{open: false}" class="absolute top-5 ml-[-7.5rem]">
            <button
                @click="open = !open"
                class="inline-flex items-center py-2 px-6 bg-gradient-to-r from-indigo-700 to-pink-600 hover:bg-opacity-95 text-white rounded-md"
            >
                <?=trans('Menu');?>
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    class="size-5 ml-2 transition-all"
                    :class="{'rotate-90' : open}"
                >
                    <path stroke-linecap="round" stroke-linejoin="round" d="m8.25 4.5 7.5 7.5-7.5 7.5" />
                </svg>
            </button>
            <ul
                x-show="open"
                @click.outside="open = false"
                x-transition
                class="bg-white shadow-md py-1"
            >
                <li>
                    <a class="py-1 px-2 hover:bg-slate-200 flex items-center" href="/admin/" class="text-indigo-600 hover:underline">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4 ml-2 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M12 21v-8.25M15.75 21v-8.25M8.25 21v-8.25M3 9l9-6 9 6m-1.5 12V10.332A48.36 48.36 0 0 0 12 9.75c-2.551 0-5.056.2-7.5.582V21M3 21h18M12 6.75h.008v.008H12V6.75Z" />
                        </svg>
                        <?=trans('Dashboard');?>
                    </a>
                </li>
                <li>
                    <a class="py-1 px-2 hover:bg-slate-200 flex items-center" href="/admin/profile/" class="text-indigo-600 hover:underline">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4 ml-2 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M18 7.5v3m0 0v3m0-3h3m-3 0h-3m-2.25-4.125a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0ZM3 19.235v-.11a6.375 6.375 0 0 1 12.75 0v.109A12.318 12.318 0 0 1 9.374 21c-2.331 0-4.512-.645-6.374-1.766Z" />
                        </svg>
                        <?=trans('Profile');?>
                    </a>
                </li>
                <li>
                    <a class="py-1 px-2 hover:bg-slate-200 flex items-center" href="/admin/users/" class="text-indigo-600 hover:underline">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4 ml-2 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M15 19.128a9.38 9.38 0 0 0 2.625.372 9.337 9.337 0 0 0 4.121-.952 4.125 4.125 0 0 0-7.533-2.493M15 19.128v-.003c0-1.113-.285-2.16-.786-3.07M15 19.128v.106A12.318 12.318 0 0 1 8.624 21c-2.331 0-4.512-.645-6.374-1.766l-.001-.109a6.375 6.375 0 0 1 11.964-3.07M12 6.375a3.375 3.375 0 1 1-6.75 0 3.375 3.375 0 0 1 6.75 0Zm8.25 2.25a2.625 2.625 0 1 1-5.25 0 2.625 2.625 0 0 1 5.25 0Z" />
                        </svg>
                        <?=trans('Users');?>
                    </a>
                </li>
                <li>
                    <a class="py-1 px-2 hover:bg-slate-200 flex items-center" href="/logout/" class="text-indigo-600 hover:underline">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-4 ml-2 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M5.636 5.636a9 9 0 1 0 12.728 0M12 3v9" />
                        </svg>
                        <?=trans('Logout');?>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
<?php endif; ?>
