<?php

declare(strict_types=1);

namespace Application\Provider;

use Codefy\Framework\Support\CodefyServiceProvider;

final class AppServiceProvider extends CodefyServiceProvider
{
    public function register(): void
    {
        // TODO: Change the autogenerated stub
    }

    public function boot(): void
    {
        // TODO: Change the autogenerated stub
    }
}
