<?php

use Codefy\Framework\Proxy\Codefy;

use function Codefy\Framework\Helpers\site_url;
use function Codefy\Framework\Helpers\trans;

?>
<!DOCTYPE html>
<html lang="<?=Codefy::$PHP->language;?>">
<head>
    <base href="<?=site_url();?>">
    <meta charset="<?=Codefy::$PHP->charset;?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="CodefyPHP Framework <?=$this->esc(Codefy::$PHP::APP_VERSION);?>">
    <title><?=$this->esc($title);?></title>
    <link rel="icon" type="image/x-icon" href="favicon.png">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 text-slate-700 font-sans">
<!-- Header -->
<header class="bg-white border-b border-slate-200 py-4 shadow-sm">
    <div class="container mx-auto px-6 flex justify-between items-center">
        <h1 class="text-xl font-semibold text-slate-800"><img src="assets/images/CodefyPHP-Banner.png" alt="codefyphp"/></h1>
        <nav class="space-x-4">
            <!-- Placeholders for login/register links -->
            <!-- Example:
        <a href="#" class="text-indigo-600 hover:underline">Login</a>
        <a href="#" class="text-indigo-600 hover:underline">Register</a>
        -->
        </nav>
    </div>
</header>
        
  <?php $this->block('dashboard'); ?>

<!-- Footer -->
<footer class="text-center text-slate-500 border-t border-slate-200 pt-8 mt-16 text-sm">
    CodefyPHP <?=Codefy::$PHP::APP_VERSION;?> • Built with <?="\u{2764}\u{FE0F}";?> ❤️ for PHP architects
</html>
