<?php

use Codefy\Framework\Proxy\Codefy;

use function Codefy\Framework\Helpers\trans;

$this->parent('framework::backend/admin-layout');
$this->block('dashboard', function ($params) {
    ?>
    
    <?=Codefy::$PHP->flash->display();?>
    
    <div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold"><?=trans('Welcome');?></h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4"><?=trans('You\'ve successfully installed CodefyPHP and created your first account.');?></p>
    </div>
  </div>

<?php }); ?>