<?php

use Codefy\Framework\Proxy\Codefy;

use function Codefy\Framework\Helpers\trans;

$this->parent('framework::backend/auth-layout');
$this->block('content', function ($params) {
    ?>
    
<main class="form-login w-100 m-auto">
<?=Codefy::$PHP->flash->display();?>
  <form class="needs-validation" method="post" action="<?=$this->esc($params['url']);?>">
    <h1 class="h3 mb-3 fw-normal"><?=trans('Please sign in');?></h1>
 
    <div class="form-floating">
      <input type="text" class="form-control" id="floatingInput" name="email" required>
      <label for="floatingInput"><?=trans('Email address');?></label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" name="password" required>
      <label for="floatingPassword"><?=trans('Password');?></label>
    </div>

    <button class="btn btn-primary w-100 py-2" type="submit"><?=trans('Sign in');?></button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; <?=date('Y');?></p>
  </form>
</main>

<?php }); ?>