<?php

use Codefy\Framework\Codefy;

use function Codefy\Framework\Helpers\config;
use function Qubus\Security\Helpers\t__;

$this->parent('framework::backend/auth-layout');
$this->block('content', function ($params) {
    ?>
    
<main class="form-login w-100 m-auto">
<?=Codefy::$PHP->flash->display();?>
  <form class="needs-validation" method="post" action="<?= config(key: 'auth.admin_url'); ?>auth/">
    <h1 class="h3 mb-3 fw-normal"><?=t__(msgid: 'Please sign in');?></h1>
 
    <div class="form-floating">
      <input type="text" class="form-control" id="floatingInput" name="username" required>
      <label for="floatingInput"><?=t__(msgid: 'Email address');?></label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" name="password" required>
      <label for="floatingPassword"><?=t__(msgid: 'Password');?></label>
    </div>
 
    <div class="form-check text-start my-3">
      <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
      <label class="form-check-label" for="flexCheckDefault">
        <?=t__(msgid: 'Remember me');?>
      </label>
    </div>

    <button class="btn btn-primary w-100 py-2" type="submit"><?=t__(msgid: 'Sign in');?></button>
    <p class="mt-5 mb-3 text-body-secondary">&copy; 2024</p>
  </form>
</main>

<?php }); ?>