<?php

use Codefy\Framework\Codefy;

use function Codefy\Framework\Helpers\config;

$this->parent('framework::backend/admin-layout');
$this->block('dashboard', function ($params) {
    ?>
    

    <div class="col-md-7 col-lg-8">
    <?=Codefy::$PHP->flash->display();?>
        <form class="needs-validation" method="post" action="<?=$this->escUrl($params['url']) ?>">
          <div class="row g-3">
            <div class="col-sm-4">
              <label for="firstName" class="form-label">First name</label>
              <input type="text" class="form-control" id="firstName" name="first_name" value="<?=$this->esc($params['user']->first_name);?>" required>
              <div class="invalid-feedback">
                Valid first name is required.
              </div>
            </div>

            <div class="col-sm-4">
              <label for="firstName" class="form-label">Middle name</label>
              <input type="text" class="form-control" id="middleName" name="middle_name" value="<?=$this->esc($params['user']->middle_name);?>">
            </div>

            <div class="col-sm-4">
              <label for="lastName" class="form-label">Last name</label>
              <input type="text" class="form-control" id="lastName" name="last_name" value="<?=$this->esc($params['user']->last_name);?>" required>
              <div class="invalid-feedback">
                Valid last name is required.
              </div>
            </div>

            <div class="col-12">
              <label for="username" class="form-label">Username</label>
              <div class="input-group has-validation">
                <span class="input-group-text">@</span>
                <input type="text" class="form-control" id="username" placeholder="Username" value="<?=$this->esc($params['user']->username);?>" disabled required>
              <div class="invalid-feedback">
                  Your username is required.
                </div>
              </div>
            </div>

            <div class="col-4">
              <label for="email" class="form-label">Email</label>
              <input type="email" class="form-control" id="email" name="email" value="<?=$this->esc($params['user']->email);?>" required>
              <div class="invalid-feedback">
                Your email is required.
              </div>
            </div>

              <div class="col-4">
                  <label for="role" class="form-label">Role</label>
                  <select class="form-control" name="role" id="role" required>
                      <option value="">Select Role</option>
                      <?php foreach($params['roles'] as $key => $value) { ?>
                      <option value="<?=$key;?>" <?=$key === $this->esc($params['user']->role) ? ' selected="selected"' : '';?>><?=$key;?></option>
                      <?php } ?>
                  </select>
                  <div class="invalid-feedback">
                      Role is required.
                  </div>
              </div>

            <div class="col-4">
              <label for="password" class="form-label">Password</label>
              <input type="password" class="form-control" id="password" name="password">
              <input type="hidden" name="user_id" value="<?=$this->esc($params['user']->user_id);?>">
            </div>
          </div>

          <hr class="my-4">

          <button class="w-100 btn btn-primary btn-lg" type="submit">Update</button>
        </form>
      </div>

      <div><br /><br /></div>

<?php }); ?>