<?php

use Codefy\Framework\Proxy\Codefy;

use function Codefy\Framework\Helpers\method_field;

$this->parent('framework::app-layout');
$this->block('content', function ($params) {
?>

<main class="flex-1 flex justify-center items-center px-6 py-10 overflow-auto">
    <form class="w-full max-w-md" method="post" action="<?=$this->url($params['url']);?>">
        <?=Codefy::$PHP->flash->display();?>
        <h2 class="text-2xl font-semibold text-slate-800 mb-6 text-center"><?=$this->trans('Update Profile');?></h2>
        <div class="mb-4">
            <label class="block text-slate-600 font-medium mb-2"><?=$this->trans('Username');?></label>
            <input type="text" class="w-full border border-slate-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500" value="<?=$this->esc($params['user']->username);?>" disabled required>
        </div>
        <div class="mb-4">
            <label class="block text-slate-600 font-medium mb-2"><?=$this->trans('First name');?></label>
            <input type="text" class="w-full border border-slate-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500" name="first_name" value="<?=$this->esc($params['user']->first_name);?>" required>
        </div>
        <div class="mb-4">
            <label class="block text-slate-600 font-medium mb-2"><?=$this->trans('Middle name');?></label>
            <input type="text" class="w-full border border-slate-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500" name="middle_name" value="<?=$this->esc($params['user']->middle_name);?>">
        </div>
        <div class="mb-4">
            <label class="block text-slate-600 font-medium mb-2"><?=$this->trans('Last name');?></label>
            <input type="text" class="w-full border border-slate-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500" name="last_name" value="<?=$this->esc($params['user']->last_name);?>" required>
        </div>
        <div class="mb-4">
            <label class="block text-slate-600 font-medium mb-2"><?=$this->trans('Email');?></label>
            <input type="email" class="w-full border border-slate-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500" name="email" value="<?=$this->esc($params['user']->email);?>" required>
        </div>
        <div class="mb-4">
            <label for="role" class="block text-slate-600 font-medium mb-2"><?=$this->trans('Role');?></label>
            <select id="role" name="role" class="border border-gray-300 text-black-50 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:border-gray-600 dark:placeholder-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500" required>
                <option selected><?=$this->trans('Select a role');?></option>
                <?php foreach($params['roles'] as $role) { ?>
                    <option value="<?=$role->value;?>" <?=$role->value === $this->esc($params['user']->role) ? ' selected="selected"' : '';?>><?=$role->label();?></option>
                <?php } ?>
            </select>
        </div>
        <div class="mb-4">
            <?=method_field(method: 'PUT');?>
            <input type="hidden" name="password">
            <input type="hidden" name="user_id" value="<?=$this->esc($params['user']->user_id);?>">
        </div>
        <button type="submit" class="bg-gradient-to-r from-indigo-700 to-pink-600 text-white px-6 py-2 rounded-lg hover:from-indigo-800 hover:to-pink-700 transition"><?=$this->trans('Update Profile');?></button>
    </form>
</main>

<hr />

<main class="flex-1 flex justify-center items-center px-6 py-10 overflow-auto">
    <form class="w-full max-w-md" method="post" action="<?=$this->url($params['url']);?>">
        <h2 class="text-2xl font-semibold text-slate-800 mb-6 text-center"><?=$this->trans('Change Password');?></h2>
        <div class="mb-4">
            <label class="block text-slate-600 font-medium mb-2"><?=$this->trans('Password');?></label>
            <input type="password" class="w-full border border-slate-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500" name="password" required>
        </div>
        <div class="mb-4">
            <label class="block text-slate-600 font-medium mb-2"><?=$this->trans('Confirm Password');?></label>
            <input type="password" class="w-full border border-slate-300 rounded-lg px-4 py-2 focus:outline-none focus:ring-2 focus:ring-indigo-500" name="confirm_password" required>
        </div>
        <div class="mb-4">
            <?=method_field('PUT');?>
            <input type="hidden" name="user_id" value="<?=$this->esc($params['user']->user_id);?>">
        </div>
        <button type="submit" class="bg-gradient-to-r from-indigo-700 to-pink-600 text-white px-6 py-2 rounded-lg hover:from-indigo-800 hover:to-pink-700 transition"><?=$this->trans('Update Password');?></button>
    </form>
</main>

<?php }); ?>